### ISSUE TITLE
vvc generator creates questionable code for multichannel vvcs

### ISSUE THREAD

**Issue by ThiemoClausen** [UVVM/UVVM#192] opened 2022-12-09 12:58 UTC
Hi,

I used the VVC generator to create a VVC with TX and RX subchannels.

This lead to the following subtype declaration in the transaction_pkg:

`subtype t_sub_channel is t_channel range TX to RX;`

The problem here is, that t_channel is declared in the uvvm_util adaption_pkg as: 
```
type t_channel is (
    NA,               -- When channel is not relevant
    ALL_CHANNELS,     -- When command shall be received by all channels
    -- UVVM predefined channels.
    RX, TX
    -- User can add more channels if needed below.
  );
```

This evaluates the range of t_sub_channel to `3 to 2`, which in turn leads to the compile error:
`(vcom-1154) No index value can belong to null index range "TX" to "RX".`

I did not spend time to check the details of the vvc_generator script, but it seems to me that a user can give any kind of channel names to the script which in turn lead to a faulty definition of the t_sub_channel.
Is this an user error? Is the user supposed to change the code inside the uvvm_utils? The comment in the definition of t_channel sure sounds like it. But even as a uvvm poweruser, this sounds like a bad idea, because it would cause annoyances when upgrading the uvvm_utils version.

kind regards
Thiemo

**Comment by am9417** [comment] 2022-12-13 08:03
You are allowed to change the code in uvvm_util library. From [uvvm_util/doc/util_quick_ref.pdf](https://github.com/UVVM/UVVM/blob/b06bce5f56a1f19a53f500b60874d0653875b461/uvvm_util/doc/util_quick_ref.pdf):
> 1.14 Adaptation package 
The adaptations_pkg.vhd is intended for local modifications to library behaviour and log layout. 
This way only one file needs to merge when a new version of the library is released. 
This package may of course also be used to set up a company or project specific behaviour and layout. 

You can use any name for the channel. But if you used some other names for the channels (like `RECEIVE` and `TRANSMIT`), the code wouldn't compile unless you added new enumerated value in the `t_channel` type, as the comment suggests.

Probably easiest way is to fix the issue is to change the range to correct manually, or the safest to re-run the script and typing the "RX" first for channel_0 name, and then "TX" for channel_1 name.

**Comment by UVVM** [comment] 2023-03-10 12:58
Fixed in release v2023.03.10

**Closed by UVVM** 2023-03-10 12:58 UTC
